//
// Created by linc on 06.06.21.
//

#ifndef AMPLITUDA_ERROR_CODE_H
#define AMPLITUDA_ERROR_CODE_H

#define FRAME_ALLOC_CODE 10
#define PACKET_ALLOC_CODE 11
#define CODEC_CONTEXT_ALLOC_CODE 12

#define FILE_OPEN_IO_CODE 20

#define CODEC_NOT_FOUND_PROC_CODE 30
#define STREAM_NOT_FOUND_PROC_CODE 31
#define STREAM_INFO_NOT_FOUND_PROC_CODE 32
#define CODEC_PARAMETERS_COPY_PROC_CODE 33
#define PACKET_SUBMITTING_PROC_CODE 34
#define CODEC_OPEN_PROC_CODE 35
#define UNSUPPORTED_SAMPLE_FMT_PROC_CODE 36
#define DECODING_PROC_CODE 37

#define SAMPLE_OUT_OF_BOUNDS_PROC_CODE 40

#endif //AMPLITUDA_ERROR_CODE_H
