//
// Created by linc on 06.06.21.
//

#ifndef AMPLITUDA_ERROR_CODE_H
#define AMPLITUDA_ERROR_CODE_H

#define ALLOC_FRAME_ERR 10
#define ALLOC_PACKET_ERR 11
#define ALLOC_CODEC_CTX_ERR 12

#define NOT_FOUND_CODEC 20
#define NOT_FOUND_STREAM 21
#define NOT_FOUND_STREAM_INFO 22

#define CODEC_PARAMETERS_ERR 31
#define PACKET_SUBMITTING_ERR 32
#define FILE_OPEN_ERR 33
#define CODEC_OPEN_ERR 34
#define UNSUPPORTED_SAMPLE_FMT 35
#define DECODING_ERR 36

#endif //AMPLITUDA_ERROR_CODE_H
